{% set name = "mdformat-myst" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_myst-{{ version }}.tar.gz
  sha256: b91cb1d8c7ec525a8cccdf5470c79c79193aa980d56af6d76cc5944b8c9f9f93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - mdformat <0.8.0,>=0.7.0
    - mdit-py-plugins >=0.3.0
    - mdformat-tables >=0.4.0
    - mdformat-frontmatter >=0.3.2
    - mdformat-footnote >=0.1.1
    - ruamel.yaml >=0.16.0

test:
  imports:
    - mdformat_myst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkinj1/mdformat-myst
  summary: Mdformat plugin for MyST compatibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
