{% set name = "mdformat-myst" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_myst-{{ version }}.tar.gz
  sha256: 9c09a9c3f4073ac7bb74159fab5d4c66fc8276e6638da05d5610ea81f803361e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7.0
    - mdit-py-plugins >=0.3.0
    - mdformat-tables >=0.4.0
    - mdformat-frontmatter >=0.3.2
    - mdformat-footnote >=0.1.1
    - ruamel.yaml >=0.16.0

test:
  imports:
    - mdformat_myst
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hukkinj1/mdformat-myst
  summary: Mdformat plugin for MyST compatibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
