{% set name = "mdformat-myst" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat_myst-{{ version }}.tar.gz
  sha256: f29974e7c66bb8df5696c68265a00fd02029c0a23acc9db7180e476099e5a24b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - mdformat >=0.7.0,<0.8.0
    - mdit-py-plugins >=0.3.0,<0.4.0
    - mdformat-tables >=0.4.0
    - mdformat-frontmatter >=0.3.2
    - ruamel.yaml >=0.16.0

test:
  imports:
    - mdformat_myst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hukkinj1/mdformat-myst
  summary: Mdformat plugin for MyST compatibility.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
